version: "3.7"
services:
  golang:
    image: template/ubuntu:1.0.0
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
        WORK_USER: work
        WORK_USER_GROUP: work
    env_file:
      - ./.env
    volumes:
      - ./work:/work
      - ./go:/go
